/**
 * Unique identifier for each type of procedure supported by the engine.
 *
 * Used to look up procedure definitions in {@link ProcedureRegistry}.
 */
export enum ProcedureId {
	Unimplemented = 'Unimplemented',
	UnimplementedAlt = 'UnimplementedAlt',

	// Core
	TriggerCapability = 'TriggerCapability',
	EmitEvent = 'EmitEvent',

	// Game sequence
	RunCampaign = 'RunCampaign',
	RunScenario = 'RunScenario',
	Chapter = 'Chapter',
	ChapterStartPhase = 'ChapterStartPhase',
	FocusPhase = 'FocusPhase',
	TurnsPhase = 'TurnsPhase',
	DrawPhase = 'DrawPhase',
	EncounterPhase = 'EncounterPhase',
	ChapterEndPhase = 'ChapterEndPhase',
	Turn = 'Turn',
	TurnStartPhase = 'TurnStartPhase',
	TurnPlayerActionsPhase = 'TurnPlayerActionsPhase',
	TurnCreatureActionsPhase = 'TurnCreatureActionsPhase',
	TurnEndPhase = 'TurnEndPhase',

	// Effects
	AddChargesEffect = 'AddChargesEffect',
	AttackEffect = 'AttackEffect',
	AttachEffect = 'AttachEffect',
	ChangeStatsEffect = 'ChangeStatsEffect',
	ChaseEffect = 'ChaseEffect',
	ConferPropertiesEffect = 'ConferPropertiesEffect',
	ConditionalEffect = 'ConditionalEffect',
	DefendEffect = 'DefendEffect',
	DiscardEffect = 'DiscardEffect',
	DiscardFromHandEffect = 'DiscardFromHandEffect',
	DrawCardsEffect = 'DrawCardsEffect',
	DrawFocusEffect = 'DrawFocusEffect',
	EngageEffect = 'EngageEffect',
	EquipEffect = 'EquipEffect',
	ExhaustEffect = 'ExhaustEffect',
	GatherCluesEffect = 'GatherCluesEffect',
	GoTowardsEffect = 'GoTowardsEffect',
	HealEffect = 'HealEffect',
	InvestigateEffect = 'InvestigateEffect',
	LooseGoldEffect = 'LooseGoldEffect',
	ModifyCapabilityCostEffect = 'ModifyCapabilityCostEffect',
	ModifyCarryingCapacityEffect = 'ModifyCarryingCapacityEffect',
	ModifyConcentrationEffect = 'ModifyConcentrationEffect',
	ModifyDamageEffect = 'ModifyDamageEffect',
	ModifyGatheredCluesEffect = 'ModifyGatheredCluesEffect',
	ModifyRollEffect = 'ModifyRollEffect',
	MoveEffect = 'MoveEffect',
	NarrationEffect = 'NarrationEffect',
	NegateDamageEffect = 'NegateDamageEffect',
	OneOfEffect = 'OneOfEffect',
	PayEffect = 'PayEffect',
	PlaceLocationEffect = 'PlaceLocationEffect',
	PlayStoryCardsEffect = 'PlayStoryCardsEffect',
	ProficiencyTableEffect = 'ProficiencyTableEffect',
	ReceiveOpportunityAttacksEffect = 'ReceiveOpportunityAttacksEffect',
	RecoverSanityEffect = 'RecoverSanityEffect',
	RedrawFateEffect = 'RedrawFateEffect',
	RedrawFocusEffect = 'RedrawFocusEffect',
	RemoveChargesEffect = 'RemoveChargesEffect',
	RepeatCapabilityEffect = 'RepeatCapabilityEffect',
	ReplaceEncounterEffect = 'ReplaceEncounterEffect',
	ReplacePropertyEffect = 'ReplacePropertyEffect',
	ResolveEncounterEffect = 'ResolveEncounterEffect',
	ResultsTableEffect = 'ResultsTableEffect',
	SanityLossEffect = 'SanityLossEffect',
	SaveTargetToVariableEffect = 'SaveTargetToVariableEffect',
	SetRollResultEffect = 'SetRollResultEffect',
	TalentEffect = 'TalentEffect',
	TestEffect = 'TestEffect',
	TransformFocusEffect = 'TransformFocusEffect',
	TriggerActionEffect = 'TriggerActionEffect',
	WoundEffect = 'WoundEffect'
}
