/* eslint-disable @typescript-eslint/no-explicit-any */

import { mapToRecord, type Type } from './utils';

const METADATA_PREFIX = '@';
const TYPE_BRAND_FIELD = `${METADATA_PREFIX}type`;
const OBJECT_POOL_FIELD = `${METADATA_PREFIX}objects`;
const KEYS_FIELD = `${METADATA_PREFIX}keys`;
const VALUES_FIELD = 'values';
const REF_FIELD = `${METADATA_PREFIX}ref`;

const STANDARD_LIBRARY_TYPES = [Set, Map];

/**
 * Defines the properties for configuring the {@link Serialisation} class.
 */
export interface SerialisationProps<ContextData> {
	/**
	 * An optional array of types that can be serialised and deserialised by this
	 * instance.
	 *
	 * In order to serialise and deserialise complex types (e.g. class instances), they
	 * must be registered in the `types` array.
	 */
	types?: Type[];

	/**
	 * A function that generates a unique brand for a given type.
	 *
	 * Type brands are used to identify the type during serialisation and deserialisation.
	 * They should be unique for each known type, and consistent across requests.
	 *
	 * By default, the type brand is generated using the type's simple name, but this can
	 * be customised to use a different naming scheme.
	 */
	typeBranding?: TypeBranding;

	/**
	 * A map of custom object mappers for specific types, allowing for custom
	 * serialisation and deserialisation logic for complex types that cannot be directly
	 * represented as JSON.
	 *
	 * If a type is not registered in this map, the default object mapper will be used,
	 * which recursively decomposes and recomposes the object's own properties.
	 */
	mappers?: Map<Type, ObjectMapper>;

	/**
	 * Rules for establishing object identity, defining how to generate unique keys for
	 * objects during serialisation, and how to retrieve the referenced objects back
	 * during deserialisation.
	 *
	 * This is used internally by the {@link Serialisation} class to support maps with
	 * complex keys, but it can also be leveraged for other scenarios where object
	 * identity matters (e.g. handling circular references).
	 */
	objectIdentity?: Map<Type, ObjectIdentity<any, ContextData>>;
}

export type TypeBranding = (type: Type) => string;

export type JSONLiteral = string | number | boolean | null;
export type JSONObject = { [key: string]: JSONValue };
export type JSONArray = JSONValue[];
export type JSONValue = JSONLiteral | JSONObject | JSONArray;

/**
 * Conditional type for method context parameters.
 * When Context already includes `undefined`, the context parameter is optional.
 * Otherwise, it is required — callers must always provide a context value.
 */
type ContextArg<Context> = undefined extends Context ? [context?: Context] : [context: Context];

/**
 * Defines a mapper for serialising and deserialising objects of a specific type.
 *
 * The `decompose` method converts an object into a JSON-compatible structure, while the
 * `recompose` method restores the original object from the JSON-compatible structure.
 *
 * This allows for custom serialisation logic for complex types that cannot be directly
 * represented as JSON, such as class instances or circular references.
 */
export interface ObjectMapper<T = unknown, ContextData = undefined> {
	decompose(data: T, context: DecomposeContext<ContextData>): JSONObject;
	recompose(data: JSONObject, context: RecomposeContext<ContextData>, target?: T): T;
}

/**
 * Defines object identity and lookup for a given type.
 *
 * This is used internally by the {@link Serialisation} class to support serialising
 * maps with complex keys, but it can also be leveraged for other scenarios where object
 * identity and lookup are required during serialisation and deserialisation (e.g.
 * handling circular references).
 */
export type ObjectIdentity<T = unknown, ContextData = undefined> = {
	/**
	 * Obtains a key for the given object, which can be used to uniquely reference it
	 * during serialisation, and to look it up during deserialisation.
	 *
	 * The key must be unique for each distinct object, and consistent across requests.
	 *
	 * @param obj The object for which to obtain a key.
	 * @param contextData Additional context data that may be used to generate the key.
	 * @returns A key that uniquely identifies the given object, or `undefined` to fall
	 *  back to inline serialisation.
	 */
	getObjectId(obj: T, contextData: ContextData): string | undefined;

	/**
	 * Indicates whether the objects of this type are external references that should not
	 * be fully serialised. When set to true, deserialisation will be dependent on
	 * contextual data. When set to false, the object will be fully serialised into a
	 * pool of objects, that can be referenced throughout the rest of the document.
	 */
	external: boolean;
} & (
	| { external: false }
	| {
			external: true;
			/**
			 * Retrieves an object by a key previously generated by the {@link getObjectId} method.
			 *
			 * @param key The key of the object to retrieve.
			 * @param contextData Additional context data that may be used to look up the object.
			 * @returns The object corresponding to the given key.
			 *
			 * @throws If the key is invalid or cannot be resolved to an object.
			 */
			resolveExternalReference(key: string, context: RecomposeContext<ContextData>): T | undefined;
	  }
);

/**
 * Common context interface for serialisation and deserialisation operations, providing
 * access to context data and path tracking functionality.
 *
 * This interface is extended by {@link DecomposeContext} and {@link RecomposeContext}
 * to provide additional methods specific to serialisation and deserialisation.
 */
interface CommonContext<ContextData = unknown> {
	/**
	 * The context data passed to the serialisation or deserialisation methods.
	 */
	data: ContextData;

	/**
	 * Executes a callback function within a specific path context, allowing for
	 * tracking of the current path during serialisation or deserialisation.
	 *
	 * @param pathComponent The path component to add to the current path.
	 * @param callback The callback function to execute within the specified path context.
	 * @returns The result of the callback function.
	 */
	withPath: <T>(pathComponent: string, callback: () => T) => T;

	/**
	 * Throws a contextualised error with the given message.
	 *
	 * @param message The error message.
	 * @returns Never returns, always throws an error.
	 * @throws An error with the given message and contextual information about the
	 *  current path in the serialisation or deserialisation process.
	 */
	fail: (message: string) => never;
}

/**
 * Context interface for serialisation operations, providing methods for decomposing
 * child objects, requiring keys for objects, and obtaining type brands.
 *
 * This interface extends {@link CommonContext} to provide additional methods specific
 * to serialisation.
 */
export interface DecomposeContext<ContextData = unknown> extends CommonContext<ContextData> {
	/**
	 * Decomposes a child key of the current object.
	 *
	 * Mappers can use this method to delegate the serialisation of nested objects
	 * to the parent {@link Serialisation} instance, allowing for recursive serialisation
	 * of complex object graphs.
	 *
	 * @param pathComponent The path component to add to the current path.
	 * @param data The data to decompose.
	 * @returns The decomposed JSON value.
	 */
	decomposeChild: (pathComponent: string, data: any) => JSONValue;

	/**
	 * Possibly obtains a unique key for the given object.
	 *
	 * Object keys can be used to serialise and deserialise maps and other structures with
	 * complex keys, to efficiently store object graphs containing multiple references to
	 * the same object or to handle circular references.
	 *
	 * In order to generate a key, the {@link Serialisation} instance must have been
	 * configured with an {@link ObjectIdentity} for the object's type. If no key can be
	 * generated, this method will return undefined.
	 *
	 * @param obj The object for which to obtain a key.
	 * @returns A key that uniquely identifies the given object, or undefined if no
	 *  suitable key could be produced.
	 */
	getObjectId: (obj: any) => string | undefined;

	/**
	 * Obtains a unique key for the given object, or throws.
	 *
	 * Object keys can be used to serialise and deserialise maps and other structures with
	 * complex keys, to efficiently store object graphs containing multiple references to
	 * the same object or to handle circular references.
	 *
	 * In order to generate a key, the {@link Serialisation} instance must have been
	 * configured with an {@link ObjectIdentity} for the object's type. If no key can be
	 * generated, this method will throw an error.
	 *
	 * @param obj The object for which to obtain a key.
	 * @returns A key that uniquely identifies the given object.
	 * @throws If a key cannot be generated for the given object.
	 */
	requireObjectId: (obj: any) => string;

	/**
	 * Obtains the type brand for a given type, which is used to identify the type during
	 * serialisation and deserialisation.
	 *
	 * @param type The type for which to obtain a brand.
	 * @returns The brand corresponding to the given type.
	 * @throws If a brand can't be generated for the given type.
	 */
	getTypeBrand: (type: Type) => string;
}

/**
 * Context interface for deserialisation operations, providing methods for recomposing
 * child objects, finding objects by key, and requiring types for brands.
 *
 * This interface extends {@link CommonContext} to provide additional methods specific
 * to deserialisation.
 */
export interface RecomposeContext<ContextData = unknown> extends CommonContext<ContextData> {
	/**
	 * Recomposes a child object from its JSON representation.
	 *
	 * Mappers can use this method to delegate the deserialisation of nested
	 * objects to the parent {@link Serialisation} instance, allowing for
	 * recursive deserialisation of complex object graphs.
	 *
	 * @param pathComponent The path component to add to the current path.
	 * @param data The JSON value to recompose.
	 * @param target If provided, the mapper should populate this object
	 *  instead of allocating a new one. Used internally to preserve object
	 *  identity for pool-resolved objects.
	 * @returns The recomposed object.
	 */
	recomposeChild: (pathComponent: string, data: JSONValue, target?: object) => any;

	/**
	 * Finds an object by its key.
	 *
	 * @param type The type of the object to find.
	 * @param key The key of the object to find.
	 * @returns The object corresponding to the given key.
	 * @throws If the key is invalid or cannot be resolved to an object.
	 */
	resolveReference: (type: Type, key: string) => any;

	/**
	 * Requires a type for a given brand.
	 *
	 * @param brand The brand for which to require a type.
	 * @returns The type corresponding to the given brand.
	 * @throws If the brand is unknown or cannot be resolved to a type.
	 */
	requireTypeForBrand: (brand: string) => Type;
}

const contextFactory = <T extends CommonContext<ContextData>, ContextData = unknown>({
	errorType,
	...props
}: Omit<T, 'withPath' | 'fail'> & {
	errorType: new (path: string[], reason: string) => SerialisationError;
}): T => {
	const path: string[] = [];
	return {
		...props,
		withPath: <X>(pathComponent: string, callback: () => X) => {
			path.push(pathComponent);
			try {
				return callback();
			} finally {
				path.pop();
			}
		},
		fail: (reason: string) => {
			throw new errorType([...path], reason);
		}
	} as unknown as T;
};

export class Serialisation<ContextData = undefined> {
	readonly typesByBrand: Record<string, Type>;
	readonly typeBranding: TypeBranding;
	readonly objectMappersByType: ReadonlyMap<Type, ObjectMapper<any, ContextData>>;
	readonly defaultObjectMapper: ObjectMapper<any, ContextData>;
	readonly objectIdentityByType: ReadonlyMap<Type, ObjectIdentity<any, ContextData>>;

	constructor({ types, typeBranding, mappers, objectIdentity }: SerialisationProps<ContextData>) {
		this.typeBranding = typeBranding ?? ((type) => type.name);
		this.objectMappersByType = mappers ?? new Map();
		this.typesByBrand = {};
		types?.forEach((type) => (this.typesByBrand[this.typeBranding(type)] = type));
		// Register standard library types with default mappers.
		for (const type of STANDARD_LIBRARY_TYPES) {
			this.typesByBrand[this.typeBranding(type)] ??= type;
		}
		this.objectIdentityByType = new Map(objectIdentity ?? new Map());
		this.defaultObjectMapper = this.createDefaultObjectMapper();
	}

	/**
	 * Serialises an object into a JSON string, using the registered object mappers and
	 * object identity rules to handle complex types and references.
	 *
	 * The serialised data can be restored using the {@link deserialise} method.
	 *
	 * Caveats:
	 * - `null` and `undefined` values are treated the same. The serialisation process will
	 *   encode undefined as `null` (valid JSON), and the deserialisation process will
	 *   decode `null` as `undefined` (the preferred in-memory representation).
	 *
	 * @param data The data to serialise.
	 * @param contextData Additional context data for the serialisation process.
	 * @returns The JSON string representation of the data.
	 */
	serialise<T>(data: T, ...contextData: ContextArg<ContextData>): string {
		const context: DecomposeContext<ContextData> = contextFactory({
			errorType: DecomposeError,
			data: contextData[0] as ContextData,
			decomposeChild: (pathComponent: string, data: any) =>
				context.withPath(pathComponent, () => this.decompose(data, context)),
			getObjectId: (obj) => this.getObjectId(obj, context.data, objectPool),
			requireObjectId: (obj) => this.requireObjectId(obj, context.data, objectPool),
			getTypeBrand: this.typeBranding
		});
		const objectPool = new ObjectPool(
			this.typeBranding,
			(obj: any, typeBrand: string, key: string) =>
				context.withPath(`@ref(${typeBrand}-${key})`, () => this.decompose(obj, context, true))
		);
		const decomposedData = this.decompose(data, context);
		objectPool.insertInto(decomposedData);
		return JSON.stringify(decomposedData ?? null);
	}

	/**
	 * Deserialises a JSON string back into an object, using the registered object mappers
	 * and object identity rules to handle complex types and references.
	 *
	 * This is the reverse of the {@link serialise} method and should be used to restore
	 * the original data structure from its JSON representation.
	 *
	 * Caveats:
	 * - `null` and `undefined` values are treated the same. The serialisation process will
	 *   encode undefined as `null` (valid JSON), and the deserialisation process will
	 *   decode `null` as `undefined` (the preferred in-memory representation).
	 *
	 * @param data The JSON string to deserialise.
	 * @param contextData Additional context data for the deserialisation process.
	 * @returns The deserialised object.
	 */
	deserialise<T>(data: string, ...contextData: ContextArg<ContextData>): T {
		const parsedData = JSON.parse(data);
		const resolvedRefs = new Map<string, any>();
		const context: RecomposeContext<ContextData> = contextFactory({
			errorType: RecomposeError,
			data: contextData[0] as ContextData,
			recomposeChild: (pathComponent: string, data: JSONValue, target?: object) =>
				context.withPath(pathComponent, () => this.recompose(data, context, target)),
			resolveReference: (type, key) =>
				this.resolveReference(type, key, context, parsedData[OBJECT_POOL_FIELD], resolvedRefs),
			requireTypeForBrand: (brand) => this.requireTypeForBrand(brand, context)
		});
		return this.recompose(parsedData, context) as T;
	}

	/**
	 * Decomposes an object to a JSON-compatible structure by recursively decomposing its
	 * properties using registered object mappers.
	 *
	 * This is the reverse of the {@link recompose} method and should be used to prepare
	 * data for serialisation.
	 *
	 * @param data The data to decompose.
	 * @returns The decomposed JSON-compatible structure.
	 */
	private decompose<T>(data: T, context: DecomposeContext<ContextData>, inline = false): JSONValue {
		if (typeof data === 'object' && data !== null) {
			if (Array.isArray(data)) {
				return data.map((item, index) => context.decomposeChild(index.toString(), item));
			} else if (data.constructor == Object) {
				return mapToRecord(data as Record<string, unknown>, {
					mapEntries: ([key, value]: [string, unknown]) => [key, context.decomposeChild(key, value)]
				});
			} else {
				const typeBrand = this.typeBranding(data.constructor as Type);

				// If object identity is defined for the object, serialise a reference to the
				// object. Disabled if `inline` is true, which is used when serialising objects
				// into the object pool, to avoid infinite recursion.
				if (!inline) {
					const key = context.getObjectId(data);
					if (key !== undefined) {
						return {
							[TYPE_BRAND_FIELD]: typeBrand,
							[REF_FIELD]: key
						};
					}
				}

				// Otherwise, serialise its state
				const objectMapper = this.getDecomposer(data);
				return {
					[TYPE_BRAND_FIELD]: typeBrand,
					...objectMapper.decompose(data, context)
				};
			}
		}
		return data as JSONValue;
	}

	/**
	 * Recomposes a JSON-compatible structure back into its original form by recursively
	 * recomposing its properties using registered object mappers.
	 *
	 * This is the reverse of the {@link decompose} method and should be used to restore
	 * the original data structure.
	 *
	 * @param data The JSON-compatible structure to recompose.
	 * @returns The recomposed original data structure.
	 */
	private recompose<T>(
		data: JSONValue,
		context: RecomposeContext<ContextData>,
		target?: object
	): T | undefined {
		if (data === null) {
			return undefined;
		}
		if (typeof data === 'object') {
			if (Array.isArray(data)) {
				return data.map((item) => this.recompose(item, context)) as unknown as T;
			} else if (TYPE_BRAND_FIELD in data) {
				const id = data[REF_FIELD];

				// If the data contains a reference field, look up the object by its key, either
				// in the context (for external references) or in the object pool (for internal
				// ones)
				if (id !== undefined) {
					const typeBrand = data[TYPE_BRAND_FIELD];
					if (typeof typeBrand !== 'string') {
						context.fail(`Invalid type brand field "${TYPE_BRAND_FIELD}" in data`);
					}
					if (typeof id !== 'string') {
						context.fail(`Invalid reference field "${REF_FIELD}" in data`);
					}
					const type = this.requireTypeForBrand(typeBrand, context);
					return context.resolveReference(type, id) as T;
				}

				// Otherwise, recompose the object using the most specific object mapper
				// available
				const objectMapper = this.getRecomposer(data, context);
				return objectMapper.recompose(data as JSONObject, context, target as T);
			} else {
				return mapToRecord(data as JSONObject, {
					mapValues: (value) => this.recompose(value, context)
				}) as unknown as T;
			}
		}
		return data as unknown as T;
	}

	private requireTypeForBrand(brand: string, context: RecomposeContext<ContextData>): Type {
		const type = this.typesByBrand[brand];
		if (!type) {
			context.fail(`Unknown type brand "${brand}"`);
		}
		return type;
	}

	private getObjectIdentity<T>(obj: T): ObjectIdentity<T, ContextData> | undefined {
		return ascendInheritanceChain(
			obj,
			(type) => this.objectIdentityByType.get(type),
			() => undefined
		);
	}

	private getObjectId(
		obj: any,
		contextData: ContextData,
		objectPool?: ObjectPool
	): string | undefined {
		// Find the identity rules for the object type
		const identity = this.getObjectIdentity(obj);
		const key = identity?.getObjectId(obj, contextData);

		if (key !== undefined && objectPool && !identity?.external) {
			objectPool.add(obj, key);
		}

		return key;
	}

	private requireObjectId(obj: any, contextData: ContextData, objectPool?: ObjectPool): string {
		const key = this.getObjectId(obj, contextData, objectPool);
		if (key === undefined) {
			throw new Error(
				`Can't produce a key for type ${obj.constructor.name}. Check the 'objectIdentity' parameter.`
			);
		}
		return key;
	}

	private resolveReference<T>(
		type: Type,
		key: string,
		context: RecomposeContext<ContextData>,
		objectPool?: JSONValue,
		resolvedRefs?: Map<string, any>
	): T | undefined {
		const objectIdentity = this.objectIdentityByType.get(type);
		if (!objectIdentity) {
			context.fail(
				`Can't find objects of type ${type.name}. Check the 'objectIdentity' parameter.`
			);
		}

		// Resolve an external reference
		if (objectIdentity.external) {
			return objectIdentity.resolveExternalReference(key, context);
		}

		// Resolve an internal reference from the object pool — use cache to
		// preserve object identity and handle circular references.
		const typeBrand = this.typeBranding(type);
		const cacheKey = `${typeBrand}:${key}`;

		if (resolvedRefs?.has(cacheKey)) {
			return resolvedRefs.get(cacheKey) as T;
		}

		// Create a placeholder and cache it before recomposition so that
		// circular references resolve to this same object.
		const instance = Object.create(type.prototype);
		resolvedRefs?.set(cacheKey, instance);

		if (typeof objectPool !== 'object' || objectPool === null || Array.isArray(objectPool)) {
			context.fail('Invalid object pool');
		}
		const typePool = objectPool[typeBrand];
		if (typeof typePool !== 'object' || typePool === null || Array.isArray(typePool)) {
			context.fail(`Invalid object pool for type ${type.name}`);
		}
		const objectData = typePool[key];
		if (objectData === undefined) {
			context.fail(`Can't find object of type ${type.name} with key "${key}"`);
		}
		if (typeof objectData !== 'object' || objectData === null || Array.isArray(objectData)) {
			context.fail(`Invalid object data for type ${type.name} with key "${key}"`);
		}

		// Resolve the pool data. recomposeChild receives the placeholder so
		// that the mapper populates it in-place rather than allocating again.
		context.recomposeChild(`@ref(${typeBrand}-${key})`, objectData, instance);

		return instance as T;
	}

	private getDecomposer<T>(obj: T): ObjectMapper<T, ContextData> {
		return ascendInheritanceChain(
			obj,
			(type) => this.objectMappersByType.get(type) ?? defaultObjectMappersByType.get(type),
			() => this.defaultObjectMapper
		);
	}

	private getRecomposer(
		data: JSONObject,
		context: RecomposeContext<ContextData>
	): ObjectMapper<any, ContextData> {
		const typeBrand = data[TYPE_BRAND_FIELD];
		if (typeof typeBrand !== 'string') {
			context.fail(`Invalid type brand field "${TYPE_BRAND_FIELD}" in data`);
		}
		const type = this.requireTypeForBrand(typeBrand, context);

		const objectMapper = this.objectMappersByType.get(type);
		if (objectMapper) {
			return objectMapper;
		}

		const defaultObjectMapperForType = defaultObjectMappersByType.get(type);
		if (defaultObjectMapperForType) {
			return defaultObjectMapperForType as ObjectMapper<any, ContextData>;
		}

		return this.defaultObjectMapper;
	}

	private createDefaultObjectMapper(): ObjectMapper<any, ContextData> {
		return {
			decompose: (data: any, context: DecomposeContext<ContextData>) => {
				const record: JSONObject = {};
				for (const key of Object.getOwnPropertyNames(data)) {
					if (!key.startsWith(METADATA_PREFIX)) {
						record[key] = context.decomposeChild(key, data[key]);
					}
				}
				return record;
			},
			recompose: (data: JSONObject, context: RecomposeContext<ContextData>, target?: any): any => {
				const typeBrand = data[TYPE_BRAND_FIELD];
				if (typeof typeBrand !== 'string') {
					context.fail(`Invalid type brand field "${TYPE_BRAND_FIELD}"`);
				}
				const type = this.typesByBrand[typeBrand];
				const obj = (target as Record<string, any>) ?? Object.create(type.prototype);
				for (const key of Object.getOwnPropertyNames(data)) {
					if (key !== TYPE_BRAND_FIELD) {
						obj[key] = context.recomposeChild(key, data[key]);
					}
				}
				return obj;
			}
		};
	}
}

class ObjectPool {
	private typeBranding: TypeBranding;
	private decomposeObject: (obj: any, typeBrand: string, key: string) => JSONValue;
	private pool: JSONObject;

	constructor(
		typeBranding: TypeBranding,
		decomposeObject: (obj: any, typeBrand: string, key: string) => JSONValue
	) {
		this.typeBranding = typeBranding;
		this.decomposeObject = decomposeObject;
		this.pool = {};
	}

	add(obj: any, key: string) {
		const type = obj.constructor as Type;
		const typeBrand = this.typeBranding(type);
		let typePool = this.pool[typeBrand] as JSONObject | undefined;
		if (!typePool) {
			typePool = {};
			this.pool[typeBrand] = typePool;
		}
		if (typePool[key] === undefined) {
			// Place a sentinel to prevent infinite recursion when decomposeObject
			// triggers getObjectId -> add for the same object.
			typePool[key] = null;
			typePool[key] = this.decomposeObject(obj, typeBrand, key);
		}
	}

	insertInto(document: JSONValue) {
		if (Object.keys(this.pool).length > 0) {
			if (typeof document !== 'object' || document === null || Array.isArray(document)) {
				throw new DecomposeError(
					[],
					'Root data must be an object when using non-external object identities'
				);
			}
			document[OBJECT_POOL_FIELD] = this.pool;
		}
	}
}

// === Default mappers for common types ===

const defaultObjectMappersByType: Map<Type, ObjectMapper<any, unknown>> = new Map();

export const registerDefaultObjectMapper = (type: Type, mapper: ObjectMapper<any, unknown>) => {
	defaultObjectMappersByType.set(type, mapper);
};

// --- Map ---

export const decomposeMap = <K, V>(obj: Map<K, V>, context: DecomposeContext): JSONObject =>
	obj.size === 0
		? {}
		: {
				[KEYS_FIELD]: context.getTypeBrand(obj.keys().next().value!.constructor as Type),
				...mapToRecord(obj, {
					mapEntries: ([key, value]) => {
						const serialisedKey = context.requireObjectId(key);
						return [serialisedKey, context.decomposeChild(serialisedKey, value)];
					}
				})
			};

export const recomposeMap = <K, V>(
	data: JSONObject,
	context: RecomposeContext,
	_target?: Map<K, V>
): Map<K, V> => {
	const map = new Map<K, V>();
	let keysType: Type | undefined = undefined;
	for (const [key, value] of Object.entries(data)) {
		if (!key.startsWith(METADATA_PREFIX)) {
			if (keysType === undefined) {
				const keyTypeBrand = data[KEYS_FIELD];
				if (typeof keyTypeBrand !== 'string') {
					context.fail(`Invalid or missing ${KEYS_FIELD} field in Map data`);
				}
				keysType = context.requireTypeForBrand(keyTypeBrand);
			}
			map.set(context.resolveReference(keysType, key), context.recomposeChild(key, value));
		}
	}
	return map;
};

registerDefaultObjectMapper(Map<any, any>, {
	decompose: decomposeMap,
	recompose: recomposeMap
});

// --- Set ---

export const decomposeSet = <T>(obj: Set<T>, context: DecomposeContext): JSONObject => ({
	values: [...obj].map((value, index) => context.decomposeChild(index.toString(), value))
});

export const recomposeSet = <T>(
	data: JSONObject,
	context: RecomposeContext,
	_target?: Set<T>
): Set<T> => {
	const rawValues = data['values'];
	if (!Array.isArray(rawValues)) {
		context.fail(`Invalid or missing ${VALUES_FIELD} field in Set data`);
	}
	return new Set(
		rawValues.map((value, index) => context.recomposeChild(index.toString(), value) as T)
	);
};

registerDefaultObjectMapper(Set<any>, {
	decompose: decomposeSet,
	recompose: recomposeSet
});

export abstract class SerialisationError extends Error {
	readonly path: string[];
	readonly reason: string;

	constructor(operation: string, path: string[], reason: string) {
		super(`${operation} error at .${path.join('.')}: ${reason}`);
		this.path = path;
		this.reason = reason;
	}
}

export class DecomposeError extends SerialisationError {
	constructor(path: string[], reason: string) {
		super('Decompose', path, reason);
	}
}

export class RecomposeError extends SerialisationError {
	constructor(path: string[], reason: string) {
		super('Recompose', path, reason);
	}
}

// === Helpers ===

const ascendInheritanceChain = <T>(
	obj: any,
	visit: (type: Type) => T | undefined,
	fallback: () => T
): T => {
	while (obj) {
		const result = visit(obj.constructor as Type);
		if (result !== undefined) {
			return result;
		}
		obj = Object.getPrototypeOf(obj);
	}
	return fallback();
};
